const pokemonsConstants = {
  GET_ALL_POKEMONS: "GET_ALL_POKEMONS",
  GET_LIMITED_POKEMONS: "GET_LIMITED_POKEMONS",
  SEARCH_POKEMONS: "SEARCH_POKEMONS",
  TYPE_SELECTED: "TYPE_SELECTED",
  LOADING: "LOADING",
};

export { pokemonsConstants };
