const pokemonsConstants = {
  GET_ALL_POKEMONS: "GET_ALL_POKEMONS",
  GET_LIMITED_POKEMONS: "GET_LIMITED_POKEMONS",
  SEARCH_POKEMONS: "SEARCH_POKEMONS",
  GET_ALL_TYPES: "GET_ALL_TYPES",
  TYPE_SELECTED: "TYPE_SELECTED",
  FILTERED_POKEMONS: "FILTERED_POKEMONS",
  CLEAR_FILTER:"CLEAR_FILTER",
  LOADING: "LOADING",
  ERROR: "ERROR",
};

export { pokemonsConstants };
