export const colorsArr = [
    { type: "fire", color: "#f87171" },
    { type: "water", color: "#06b6d4" },
    { type: "grass", color: "#84cc16" },
    { type: "bug", color: "#22c55e" },
    { type: "ice", color: "#60a5fa" },
    { type: "normal", color: "#94a3b8" },
    { type: "poison", color: "#14b8a6" },
    { type: "electric", color: "#f59e0b" },
    { type: "ground", color: "#ca8a04" },
    { type: "fairy", color: "#fb923c" },
    { type: "fighting", color: "#fb7185" },
    { type: "flying", color: "#a78bfa" },
    { type: "rock", color: "#a16207" },
    { type: "ghost", color: "#6b7280" },
    { type: "psychic", color: "#818cf8" },
    { type: "dragon", color: "#c084fc" },
    { type: "dark", color: "#64748b" },
    { type: "shadow", color: "#9ca3af" },
    { type: "steel", color: "#78716c" },
    { type: "unknown", color: "#f472b6" },
  ];